version = 1
[[annotations]]
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"
path = [".envrc", ".gitignore", "shell.nix"]
precedence = "closest"

[[annotations]]
SPDX-FileCopyrightText = "Tom Hubrecht <tom.hubrecht@ens-lyon.fr>"
SPDX-License-Identifier = "MIT"
path = ".github/workflows/*"
precedence = "closest"
